build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.13
  amd64: ghcr.io/home-assistant/amd64-base:3.13
  armhf: ghcr.io/home-assistant/armhf-base:3.13
  armv7: ghcr.io/home-assistant/armv7-base:3.13
  i386: ghcr.io/home-assistant/i386-base:3.13
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  ZWAVEJS_SERVER_VERSION: 1.15.0
  ZWAVEJS_VERSION: 8.11.6
